# Generated by Django 2.0.7 on 2018-07-15 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_statements', models.TextField(help_text='Answer submitted to the question.')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Description of the question shown to the student.')),
                ('code_pre_statements', models.TextField(blank=True, help_text='Python statements prior to the student answer area.', null=True)),
                ('code_post_statements', models.TextField(blank=True, help_text='Python statements after the student answer area.', null=True)),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='intro_python.Question'),
        ),
    ]
